--- #YAML:1.0
name:               WWW-CurlOO
version:            0.11_51
abstract:           Perl interface for libcurl
author:
    - Przemysław Iskra <sparky at pld-linux.org>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    ExtUtils::MakeMaker::Config:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:        0
    perl:              5.008001
    Scalar::Util:      0
    Test::CPAN::Meta:  0
    Test::More:        0
    Test::Pod:         0
resources:
    repository:  https://github.com/sparky/perl-WWW-CurlOO
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
