--- #YAML:1.0
name:               WWW-CurlOO
version:            0.03
abstract:           Perl interface for libcurl
author:
    - Przemysław Iskra <sparky at pld-linux.org>
license:            MPL or MIT/X-derivate
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.008001
resources:
    repository:  https://github.com/sparky/perl-WWW-CurlOO
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
